name = "cf-bench-react-vite"
compatibility_date = "2025-12-19"
main = "worker/index.ts"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "none"
html_handling = "drop-trailing-slash"
