name = "cf-bench-sveltekit"
compatibility_date = "2025-12-19"
compatibility_flags = ["nodejs_compat"]

main = ".svelte-kit/cloudflare/_worker.js"

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"
html_handling = "drop-trailing-slash"
