name = "cf-bench-react-spa"
compatibility_date = "2025-12-19"
main = "worker/index.ts"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
html_handling = "drop-trailing-slash"
