name = "cf-bench-astro"
compatibility_date = "2025-12-19"
compatibility_flags = ["nodejs_compat"]
main = "./dist/_worker.js/index.js"

[assets]
directory = "./dist"
binding = "ASSETS"
html_handling = "drop-trailing-slash"
